# Generated by Django 5.0.4 on 2024-05-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_service_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(blank=True, choices=[('watching', 'Рассмотрение'), ('accepted', 'Принят'), ('denied', 'Отклонён')], default='watching', max_length=100, null=True, verbose_name='Статус услуги'),
        ),
    ]
