# Generated by Django 5.0.4 on 2024-05-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_service_options_alter_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, default='category/default.jpg', null=True, upload_to='category/'),
        ),
    ]
