# Generated by Django 5.0.6 on 2024-06-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_provider_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='status',
            field=models.CharField(blank=True, choices=[('Рассмотрение', 'Рассмотрение'), ('Принят', 'Принят'), ('Отклонён', 'Отклонён')], default='Рассмотрение', max_length=100, null=True, verbose_name='Статус страницы пользователя'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
    ]
