# Generated by Django 5.0.6 on 2024-06-14 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_provider_status_alter_reviews_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='extra',
        ),
    ]
