# Generated by Django 5.0.6 on 2024-06-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_service_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='best_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='best_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
