# Generated by Django 5.0.4 on 2024-05-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
